language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install -U pip
  - pip install -e .[testing]
  - pip install coveralls

script: py.test src/ --cov=src/ --cov-report term-missing

after_success:
  - coveralls

notifications:
email: false
