language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

script: - py.test src/ --cov=src/ --cov-report term-missing

after_success:
  -coveralls

notifications:
email: false
